<?php
/**
 * EventTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenParty API
 *
 * Move your app forward with the OpenParty API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EventTest Class Doc Comment
 *
 * @category    Class */
// * @description Event
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EventTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Event"
     */
    public function testEvent()
    {

    }

    /**
     * Test attribute "event_id"
     */
    public function testPropertyEventId()
    {

    }

    /**
     * Test attribute "event_title"
     */
    public function testPropertyEventTitle()
    {

    }

    /**
     * Test attribute "age_minimum"
     */
    public function testPropertyAgeMinimum()
    {

    }

    /**
     * Test attribute "event_description"
     */
    public function testPropertyEventDescription()
    {

    }

    /**
     * Test attribute "flyer_filename"
     */
    public function testPropertyFlyerFilename()
    {

    }

    /**
     * Test attribute "flyer_uri"
     */
    public function testPropertyFlyerUri()
    {

    }

    /**
     * Test attribute "music_genres"
     */
    public function testPropertyMusicGenres()
    {

    }

    /**
     * Test attribute "event_date"
     */
    public function testPropertyEventDate()
    {

    }

    /**
     * Test attribute "start_time"
     */
    public function testPropertyStartTime()
    {

    }

    /**
     * Test attribute "event_subtitle"
     */
    public function testPropertyEventSubtitle()
    {

    }

    /**
     * Test attribute "venue"
     */
    public function testPropertyVenue()
    {

    }

    /**
     * Test attribute "featured"
     */
    public function testPropertyFeatured()
    {

    }

}
