<?php
/**
 * VenueTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenParty API
 *
 * Move your app forward with the OpenParty API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VenueTest Class Doc Comment
 *
 * @category    Class */
// * @description Venue
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VenueTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Venue"
     */
    public function testVenue()
    {

    }

    /**
     * Test attribute "venue_id"
     */
    public function testPropertyVenueId()
    {

    }

    /**
     * Test attribute "venue_type"
     */
    public function testPropertyVenueType()
    {

    }

    /**
     * Test attribute "venue_title"
     */
    public function testPropertyVenueTitle()
    {

    }

    /**
     * Test attribute "venue_display_title"
     */
    public function testPropertyVenueDisplayTitle()
    {

    }

    /**
     * Test attribute "venue_description"
     */
    public function testPropertyVenueDescription()
    {

    }

    /**
     * Test attribute "venue_features"
     */
    public function testPropertyVenueFeatures()
    {

    }

    /**
     * Test attribute "venue_policy"
     */
    public function testPropertyVenuePolicy()
    {

    }

    /**
     * Test attribute "neighborhood"
     */
    public function testPropertyNeighborhood()
    {

    }

    /**
     * Test attribute "address_street"
     */
    public function testPropertyAddressStreet()
    {

    }

    /**
     * Test attribute "address_city"
     */
    public function testPropertyAddressCity()
    {

    }

    /**
     * Test attribute "address_state"
     */
    public function testPropertyAddressState()
    {

    }

    /**
     * Test attribute "address_postal_code"
     */
    public function testPropertyAddressPostalCode()
    {

    }

    /**
     * Test attribute "address_country"
     */
    public function testPropertyAddressCountry()
    {

    }

    /**
     * Test attribute "temporarily_closed"
     */
    public function testPropertyTemporarilyClosed()
    {

    }

    /**
     * Test attribute "operating_hours"
     */
    public function testPropertyOperatingHours()
    {

    }

    /**
     * Test attribute "operating_hours_list"
     */
    public function testPropertyOperatingHoursList()
    {

    }

    /**
     * Test attribute "check_in_time"
     */
    public function testPropertyCheckInTime()
    {

    }

    /**
     * Test attribute "venue_area_size"
     */
    public function testPropertyVenueAreaSize()
    {

    }

    /**
     * Test attribute "capacity"
     */
    public function testPropertyCapacity()
    {

    }

    /**
     * Test attribute "age_minimum"
     */
    public function testPropertyAgeMinimum()
    {

    }

    /**
     * Test attribute "crowd_type"
     */
    public function testPropertyCrowdType()
    {

    }

    /**
     * Test attribute "dress_code"
     */
    public function testPropertyDressCode()
    {

    }

    /**
     * Test attribute "price_rating"
     */
    public function testPropertyPriceRating()
    {

    }

    /**
     * Test attribute "music_genres"
     */
    public function testPropertyMusicGenres()
    {

    }

    /**
     * Test attribute "venue_rooms"
     */
    public function testPropertyVenueRooms()
    {

    }

    /**
     * Test attribute "venue_facebook"
     */
    public function testPropertyVenueFacebook()
    {

    }

    /**
     * Test attribute "venue_instagram"
     */
    public function testPropertyVenueInstagram()
    {

    }

    /**
     * Test attribute "venue_logo"
     */
    public function testPropertyVenueLogo()
    {

    }

    /**
     * Test attribute "venue_videos"
     */
    public function testPropertyVenueVideos()
    {

    }

    /**
     * Test attribute "venue_images"
     */
    public function testPropertyVenueImages()
    {

    }

}
