<?php

namespace AppBundle\Repository;

/**
 * GameStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameStatRepository extends \Doctrine\ORM\EntityRepository
{
}
